[package]
name = "wavebreaker_sdl2"
version = "0.1.0"
authors = ["Zeno <zeno@oxydyze.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sdl2 = {version = "0.34", features = ['ttf'] }
